version: '3.8'

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb_nutricion
    ports:
      - "8001:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    networks:
      - red_nutricional

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: api_nutricion
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DYNAMODB_ENDPOINT_URL=${DYNAMODB_ENDPOINT_URL}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-2}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-mock}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-mock}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_APP_CLIENT_ID=${COGNITO_APP_CLIENT_ID}
    depends_on:
      dynamodb:
        condition: service_started
    networks:
      - red_nutricional

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_nutricion
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - red_nutricional

networks:
  red_nutricional:
    driver: bridge


