version: '3.8'

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb_nutricion
    ports:
      - "8001:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    networks:
      - red_nutricional

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: api_nutricion
    ports:
      - "8000:8000"
    environment:
      - DYNAMODB_ENDPOINT_URL=http://dynamodb:8000
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=mock
      - AWS_SECRET_ACCESS_KEY=mock
    depends_on:
      dynamodb:
        condition: service_started
    networks:
      - red_nutricional

networks:
  red_nutricional:
    driver: bridge


